Use dlang @property functions instead of get/set functions
capnproto/capnproto-dlang pull request #7
Opened 2017-07-10 07:47 UTC by kookman

This allows more idiomatic dlang usage of generated models. Addresses #5. Only remaining case is where setting a Void.VOID value. To disambiguate from reading property, the write function is still set... function (see addressbook sample: unemployed for an example).

2017-07-10 08:57 UTC, ThomasBrixLarsen commented
I would prefer it if the old syntax is kept as aliases to be closer to the C++/Java documentation and to lessen the burden on projects already using capnproto-dlang. This also makes the case of setUnemployed stand out less.

2017-07-11 10:58 UTC, kookman commented
Good idea, I've updated the PR now.

2017-07-11 11:14 UTC, ThomasBrixLarsen requested changes
Overall looking good.

2017-07-11 11:14 UTC, ThomasBrixLarsen commented on compiler/src/main/cpp/capnpc-dlang.c++
> +            ),
There is something with the spacing on this line.

2017-07-11 11:14 UTC, ThomasBrixLarsen commented on source/samples/mmap.d
> +    alice.email = "alice@example.com";
Spacing.

2017-07-11 11:14 UTC, ThomasBrixLarsen commented on source/samples/test.d
> +    alice.email = "alice@example.com";
Spacing.

2017-07-11 11:14 UTC, ThomasBrixLarsen commented on source/samples/addressbook.d
> +	  0x21,0x0,0x0,0x0,0x1,0x0,0x1,0x0,
I'm a little concerned that this has changed. I don't see how this change could cause this. Perhaps I forgot to update the pregenerated files after an earlier update.

2017-07-11 11:35 UTC, kookman commented on source/samples/addressbook.d
> +	  0x21,0x0,0x0,0x0,0x1,0x0,0x1,0x0,
I don't think this is to do with the change. I believe this may have been "stale" in the existing file - is that possible?

2017-07-11 11:37 UTC, ThomasBrixLarsen commented on source/samples/addressbook.d
> +	  0x21,0x0,0x0,0x0,0x1,0x0,0x1,0x0,
Yes that is what I think as well.

2017-07-11 11:37 UTC, ThomasBrixLarsen approved these changes

2017-07-11 11:38 UTC, merged